//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avolutions.Baf.Domain.Articles.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ArticleResources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArticleResources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avolutions.Baf.Domain.Articles.Resources.ArticleResources.de", typeof(ArticleResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        internal static string article_type_product {
            get {
                return ResourceManager.GetString("article-type.product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dienstleistung.
        /// </summary>
        internal static string article_type_service {
            get {
                return ResourceManager.GetString("article-type.service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikel-Nr..
        /// </summary>
        internal static string field_article_no {
            get {
                return ResourceManager.GetString("field.article-no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        internal static string field_description {
            get {
                return ResourceManager.GetString("field.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis.
        /// </summary>
        internal static string field_price {
            get {
                return ResourceManager.GetString("field.price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mengeneinheit.
        /// </summary>
        internal static string field_quantity_unit {
            get {
                return ResourceManager.GetString("field.quantity-unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezeichung.
        /// </summary>
        internal static string field_title {
            get {
                return ResourceManager.GetString("field.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikeltyp.
        /// </summary>
        internal static string field_type {
            get {
                return ResourceManager.GetString("field.type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikel.
        /// </summary>
        internal static string name_plural {
            get {
                return ResourceManager.GetString("name.plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikel.
        /// </summary>
        internal static string name_singular {
            get {
                return ResourceManager.GetString("name.singular", resourceCulture);
            }
        }
    }
}
