//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avolutions.Baf.Domain.Articles.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ArticleResources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArticleResources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avolutions.Baf.Domain.Articles.Resources.ArticleResources.de", typeof(ArticleResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        internal static string ArticleType_Product {
            get {
                return ResourceManager.GetString("ArticleType.Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dienstleistung.
        /// </summary>
        internal static string ArticleType_Service {
            get {
                return ResourceManager.GetString("ArticleType.Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikel-Nr..
        /// </summary>
        internal static string Field_ArticleNo {
            get {
                return ResourceManager.GetString("Field.ArticleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        internal static string Field_Description {
            get {
                return ResourceManager.GetString("Field.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis.
        /// </summary>
        internal static string Field_Price {
            get {
                return ResourceManager.GetString("Field.Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mengeneinheit.
        /// </summary>
        internal static string Field_QuantityUnit {
            get {
                return ResourceManager.GetString("Field.QuantityUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezeichung.
        /// </summary>
        internal static string Field_Title {
            get {
                return ResourceManager.GetString("Field.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikeltyp.
        /// </summary>
        internal static string Field_Type {
            get {
                return ResourceManager.GetString("Field.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikel.
        /// </summary>
        internal static string Name_Plural {
            get {
                return ResourceManager.GetString("Name.Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikel.
        /// </summary>
        internal static string Name_Singular {
            get {
                return ResourceManager.GetString("Name.Singular", resourceCulture);
            }
        }
    }
}
