//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avolutions.Baf.Domain.Calendar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CalendarResources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalendarResources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avolutions.Baf.Domain.Calendar.Resources.CalendarResources.de", typeof(CalendarResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminart.
        /// </summary>
        internal static string Field_CalendarEventType {
            get {
                return ResourceManager.GetString("Field.CalendarEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        internal static string Field_Description {
            get {
                return ResourceManager.GetString("Field.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende.
        /// </summary>
        internal static string Field_End {
            get {
                return ResourceManager.GetString("Field.End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganztägig.
        /// </summary>
        internal static string Field_IsAllDay {
            get {
                return ResourceManager.GetString("Field.IsAllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Field_Start {
            get {
                return ResourceManager.GetString("Field.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        internal static string Field_Title {
            get {
                return ResourceManager.GetString("Field.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichtbarkeit.
        /// </summary>
        internal static string Field_Visibility {
            get {
                return ResourceManager.GetString("Field.Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termine.
        /// </summary>
        internal static string Name_Plural {
            get {
                return ResourceManager.GetString("Name.Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin.
        /// </summary>
        internal static string Name_Singular {
            get {
                return ResourceManager.GetString("Name.Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei ganztägigen Terminen muss das Ende auf Mitternacht liegen..
        /// </summary>
        internal static string Validation_AllDayEndMustBeMidnight {
            get {
                return ResourceManager.GetString("Validation.AllDayEndMustBeMidnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei ganztägigen Terminen muss der Beginn auf Mitternacht liegen..
        /// </summary>
        internal static string Validation_AllDayStartMustBeMidnight {
            get {
                return ResourceManager.GetString("Validation.AllDayStartMustBeMidnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privat.
        /// </summary>
        internal static string Visibility_Private {
            get {
                return ResourceManager.GetString("Visibility.Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffentlich.
        /// </summary>
        internal static string Visibility_Public {
            get {
                return ResourceManager.GetString("Visibility.Public", resourceCulture);
            }
        }
    }
}
